export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_USER: "LOGOUT_USER",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE"
}

export const categoryConstant = {
    GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE'
}

export const productConstant = {
    GET_PRODUCT_REQUEST: ' GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
    GET_PRODUCT_PAGE_REQUEST: ' GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',
    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
}


export const cartConstant = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    RESET_CART: 'RESET_CART',
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE"
}

export const userConstant = {
    ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',
    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',
    ADD_USER_ORDER_REQUEST: 'ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS: 'ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILURE: 'ADD_USER_ORDER_FAILURE',
    GET_USER_ORDERS_REQUEST: 'GET_USER_ORDERS_REQUEST',
    GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS',
    GET_USER_ORDERS_FAILURE: 'GET_USER_ORDERS_FAILURE',
    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
}

