export const authConstant = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGOUT_USER : "LOGOUT_USER",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE"
}

export const userConstant = {
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILURE : "SIGNUP_FAILURE"
}

export const categoryConstant={
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE:'GET_CATEGORY_FAILURE',
    ADD_CATEGORY_REQUEST:'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS:'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE:'ADD_CATEGORY_FAILURE',
    UPDATE_CATEGORY_REQUEST:'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS:'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE:'UPDATE_CATEGORY_FAILURE',
    DELETE_CATEGORY_REQUEST:'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS:'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE:'DELETE_CATEGORY_FAILURE'
}


export const productConstant={
    ADD_PRODUCT_REQUEST:'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS:'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE:'ADD_PRODUCT_FAILURE',
    GET_PRODUCTS_REQUEST:'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS:'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE:'GET_PRODUCTS_FAILURE'

}

export const pageConstant = {
    CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE'
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };